// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBONSk4YlqZDqKhISKFPjbqrjYsygNnZs',
    appId: '1:1055795974148:android:fddf7c76c10ad5a3cfa551',
    messagingSenderId: '1055795974148',
    projectId: 'project-memorable',
    databaseURL: 'https://project-memorable-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project-memorable.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGKtcLhI9FpY2EjCrMCYaVeDD-euaLdmY',
    appId: '1:1055795974148:ios:59c20c568cb879e9cfa551',
    messagingSenderId: '1055795974148',
    projectId: 'project-memorable',
    databaseURL: 'https://project-memorable-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project-memorable.appspot.com',
    iosClientId: '1055795974148-8ct8vk323ldmkdqhdlb45q51h12flmpp.apps.googleusercontent.com',
    iosBundleId: 'com.yeonrok.projectMemorable',
  );

}